-- NV CO BAN
select * from QL_TRUONGHOC_X.V_PERSONAL_INF_NHANSU; 
BEGIN QL_TRUONGHOC_X.UPDATE_PHONE('1234567890'); END;
SELECT * FROM QL_TRUONGHOC_X.KHMO_CHITIET;
SELECT * FROM QL_TRUONGHOC_X.HOCPHAN;
select * from QL_TRUONGHOC_X.DONVI_CHITIET;
SELECT * FROM QL_TRUONGHOC_X.SINHVIEN;