-- NV CO BAN
select * from QL_TRUONGHOC_X.V_PERSONAL_INF_NHANSU; 
BEGIN QL_TRUONGHOC_X.UPDATE_PHONE('1234567891'); END;/
SELECT * FROM QL_TRUONGHOC_X.KHMO_CHITIET;
SELECT * FROM QL_TRUONGHOC_X.HOCPHAN;
select * from QL_TRUONGHOC_X.DONVI_CHITIET;
SELECT * FROM QL_TRUONGHOC_X.SINHVIEN;

-- Giang Vien
SELECT * FROM QL_TRUONGHOC_X.PHANCONG_MY_INFO;
SELECT * FROM QL_TRUONGHOC_X.DK_MY_CLASSES;

BEGIN
    QL_TRUONGHOC_X.UPDATE_GRADES(10,10,10, 10,'HP005', 'SV005543', 1, 2023, 'VP');
END;

-- Truong DV
SELECT * FROM QL_TRUONGHOC_X.PHANCONG_TRUONGDONVI;
SELECT * FROM QL_TRUONGHOC_X.TRUONGDONVI_NHANSU;

BEGIN QL_TRUONGHOC_X.DELETE_PHANCONG(:P_MANV,:P_MAHP,:P_HK,:P_NAM,:P_CT); END;
BEGIN QL_TRUONGHOC_X.UPDATE_PHANCONG(:P_MANV,:P_MAHP,:P_HK,:P_NAM,:P_CT,:P_NEW_MANV); END;
BEGIN QL_TRUONGHOC_X.ADD_PHANCONG(:P_MANV,:P_MAHP,:P_HK,:P_NAM,:P_CT); END;
