-- select count(*) from QL_TRUONGHOC_X.HOCPHAN
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP001', 'IT Innovation', 5, 45, 30, 55, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP002', 'IT Implementation', 6, 45, 45, 31, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP003', 'IT Infrastructure', 6, 15, 75, 33, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP004', 'IT Risk Management', 5, 15, 60, 24, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP005', 'IT Change Management', 6, 30, 60, 54, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP006', 'Cryptocurrency', 6, 30, 60, 40, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP007', 'IT Evaluation', 5, 15, 60, 18, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP008', 'Big Data', 5, 45, 30, 41, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP009', 'IT Maintenance', 5, 45, 30, 25, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP010', 'IT Disaster Recovery', 4, 15, 45, 57, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP011', 'IT Revolution', 4, 15, 45, 21, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP012', 'IT Evolution', 4, 15, 45, 33, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP013', 'IT Adoption', 4, 30, 30, 29, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP014', 'Robotics', 5, 15, 60, 54, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP015', 'IT Evaluation', 5, 30, 45, 21, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP016', 'IT Governance', 5, 30, 45, 39, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP017', 'IT Analysis', 4, 45, 15, 43, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP018', 'IT Governance', 6, 15, 75, 30, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP019', 'Network Security', 4, 15, 45, 38, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP020', 'Augmented Reality', 6, 30, 60, 25, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP021', 'Network Security', 5, 15, 60, 22, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP022', 'Network Security', 4, 45, 15, 52, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP023', 'IT Service Management', 5, 45, 30, 28, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP024', 'IT Auditing', 6, 15, 75, 30, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP025', 'IT Troubleshooting', 4, 30, 30, 33, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP026', 'IT Recruitment', 4, 45, 15, 64, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP027', 'Internet of Things', 4, 15, 45, 34, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP028', 'Cloud Computing', 4, 45, 15, 42, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP029', 'IT Operations', 4, 45, 15, 64, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP030', 'E-commerce', 6, 45, 45, 15, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP031', 'IT Support', 4, 45, 15, 61, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP032', 'IT Outsourcing', 4, 15, 45, 53, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP033', 'Internet of Things', 6, 30, 60, 49, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP034', 'Data Analytics', 5, 15, 60, 23, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP035', 'Blockchain', 5, 15, 60, 47, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP036', 'Blockchain', 4, 30, 30, 38, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP037', 'IT Vendor Management', 4, 45, 15, 38, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP038', 'Augmented Reality', 6, 15, 75, 28, 'KHMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP039', 'Data Privacy', 5, 15, 60, 55, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP040', 'Social Media Analytics', 5, 15, 60, 55, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP041', 'Data Analytics', 5, 45, 30, 60, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP042', 'Information Security', 6, 45, 45, 37, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP043', 'Artificial Intelligence', 6, 45, 45, 38, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP044', 'User Experience Design', 6, 30, 60, 58, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP045', 'IT Revolution', 5, 30, 45, 29, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP046', 'Web Development', 4, 15, 45, 56, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP047', 'IT Vendor Management', 6, 15, 75, 25, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP048', 'IT Performance Management', 4, 15, 45, 52, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP049', 'Virtual Reality', 4, 45, 15, 25, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP050', 'IT Adoption', 6, 15, 75, 39, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP051', 'Virtual Reality', 4, 30, 30, 64, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP052', 'Machine Learning', 5, 30, 45, 26, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP053', 'IT Integration', 4, 45, 15, 43, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP054', 'Cloud Computing', 4, 30, 30, 39, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP055', 'IT Vendor Management', 5, 15, 60, 48, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP056', 'Blockchain', 5, 30, 45, 22, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP057', 'Internet of Things', 6, 15, 75, 28, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP058', 'IT Evaluation', 6, 45, 45, 55, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP059', 'IT Adoption', 4, 30, 30, 19, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP060', 'Robotics', 6, 30, 60, 16, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP061', 'Data Privacy', 4, 30, 30, 41, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP062', 'Artificial Intelligence', 5, 15, 60, 37, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP063', 'Digital Marketing', 5, 15, 60, 56, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP064', 'IT Integration', 4, 15, 45, 49, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP065', 'Cryptocurrency', 6, 45, 45, 22, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP066', 'Information Security', 4, 30, 30, 56, 'CNPM1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP067', 'IT Strategy', 6, 15, 75, 35, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP068', 'Natural Language Processing', 6, 30, 60, 19, 'CNTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP069', 'Quantum Computing', 5, 30, 45, 58, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP070', 'Natural Language Processing', 5, 15, 60, 43, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP071', 'IT Automation', 6, 45, 45, 28, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP072', 'IT Maintenance', 4, 30, 30, 33, 'TGMT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP073', 'IT Quality Assurance', 5, 15, 60, 42, 'HTTT1');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP074', 'E-commerce', 5, 15, 60, 62, 'MMTVT');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP075', 'IT Service Desk', 4, 45, 15, 23, 'HTTT1');

insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP076', 'Soft Skill', 6, 45, 45, 28, 'VPK01');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP077', 'Automation', 4, 30, 30, 33, 'VPK01');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP078', 'Quality Assurance', 5, 15, 60, 42, 'VPK01');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP079', 'E-commerce', 5, 15, 60, 62, 'VPK01');
insert into QL_TRUONGHOC_X.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) values ('HP080', 'Service Desk', 4, 45, 15, 23, 'VPK01');