EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('NHANVIENCOBAN', 'MANV', 'NHANSU', 'VAITRO', 'Nhan vien co ban');
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('GIANGVIEN', 'MANV', 'NHANSU', 'VAITRO', 'Giang vien');
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('TRUONGKHOA', 'MANV', 'NHANSU', 'VAITRO', 'Truong khoa');
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('TRUONGDONVI', 'MANV', 'NHANSU', 'VAITRO', 'Truong don vi');
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('GIAOVU', 'MANV', 'NHANSU', 'VAITRO', 'Giao vu');
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES_NO_CONDITION('SINHVIEN', 'MASV', 'SINHVIEN');
-- SELECT count(*) FROM DBA_ROLE_PRIVS where GRANTED_ROLE like 'RL_TRUONGHOC_SINHVIEN';

DECLARE
    CURSOR CUR_USR IS ( 
        SELECT USERNAME FROM dba_users
        WHERE username like 'X_NS%' or username like 'X_SV%'
    );
BEGIN
    FOR USR IN CUR_USR LOOP
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || USR.USERNAME ;
    END LOOP;
END;
/