---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_USERS
AS
        SELECT USERNAME FROM DBA_USERS;
    
/
-- GÁN QUUYEN XEM VIEW CHO USER/ROLE
REVOKE SELECT ON VIEW_USERS FROM QUANTRI_CSDL;
GRANT SELECT ON VIEW_USERS TO C##QUANTRI1;

---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_ROLES
AS
    SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE '';
/
-- GÁN QUUYEN XEM VIEW CHO USER/ROLE
REVOKE SELECT ON VIEW_ROLES FROM QUANTRI_CSDL;
GRANT SELECT ON VIEW_ROLES TO C##QUANTRI1;
---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_TABLES
AS
    SELECT * FROM DBA_TABLES;
/
-- GÁN QUUYEN XEM VIEW CHO USER/ROLE
REVOKE SELECT ON VIEW_TABLES FROM QUANTRI_CSDL;
GRANT SELECT ON VIEW_TABLES TO C##QUANTRI1;
---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_USERS_PRIVS
AS
    SELECT * FROM USER_SYS_PRIVS;
/
-- GÁN QUUYEN XEM VIEW CHO USER/ROLE
REVOKE SELECT ON VIEW_USERS_PRIVS FROM QUANTRI_CSDL;
GRANT SELECT ON VIEW_USERS_PRIVS TO C##QUANTRI1;
---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_ROLES_PRIVS
AS
    SELECT * FROM DBA_ROLE_PRIVS;
/
-- GÁN QUUYEN XEM VIEW CHO USER/ROLE
REVOKE SELECT ON VIEW_ROLES_PRIVS FROM QUANTRI_CSDL;
GRANT SELECT ON VIEW_ROLES_PRIVS TO C##QUANTRI1;
---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_TAB_PRIVS
AS
    SELECT * FROM DBA_TAB_PRIVS;
/
REVOKE SELECT ON VIEW_TAB_PRIVS FROM QUANTRI_CSDL;
GRANT SELECT ON VIEW_TAB_PRIVS TO C##QUANTRI1;

---------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE TAO USER MOI
CREATE OR REPLACE PROCEDURE CREATE_USER(
    P_USERNAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2
)
--AUTHID CURRENT_USER 
AS
BEGIN
    EXECUTE IMMEDIATE ('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
    EXECUTE IMMEDIATE ('CREATE USER ' || P_USERNAME || ' IDENTIFIED BY ' || P_PASSWORD);
    EXECUTE IMMEDIATE ('GRANT CREATE SESSION TO '|| P_USERNAME );
END;
/
-- THUC THI PROCEDURE CREATE_USER
BEGIN
    CREATE_USER('C##QUANTRI1', '1234');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE XOA USER
CREATE OR REPLACE PROCEDURE DROP_USER(P_USERNAME IN VARCHAR2) 
AUTHID CURRENT_USER 
AS
BEGIN
        EXECUTE IMMEDIATE ('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
    EXECUTE IMMEDIATE ('DROP USER ' || P_USERNAME);
END;
/
-- THUC THI PROCEDURE DROP_USER
BEGIN
    DROP_USER('C##TNN');
END;

---------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE SUA(HIEU CHINH) USER
CREATE OR REPLACE PROCEDURE ALTER_USER(
    P_USERNAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2) 
AUTHID CURRENT_USER 
AS
BEGIN
    EXECUTE IMMEDIATE ('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
   EXECUTE IMMEDIATE ('ALTER USER ' || P_USERNAME ||' IDENTIFIED BY '|| P_PASSWORD);
END;
/
-- THUC THI PROCEDURE DROP_USER
BEGIN
    ALTER_USER('TMP2', '123');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE THEM ROLE
CREATE OR REPLACE PROCEDURE CREATE_ROLE(
    P_ROLENAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2
)
AUTHID CURRENT_USER 
AS
BEGIN
    EXECUTE IMMEDIATE ('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
    IF(P_PASSWORD = ' ') THEN
        EXECUTE IMMEDIATE ('CREATE ROLE ' || P_ROLENAME);
    END IF;
    EXECUTE IMMEDIATE ('CREATE ROLE ' || P_ROLENAME ||' IDENTIFIED BY '||P_PASSWORD);
END;
/
-- THUC THI PROCEDURE CREATE_USER
BEGIN
    CREATE_ROLE('QUANTRI_CSDL','QUANTRI_CSDL');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE XOA ROLE
CREATE OR REPLACE PROCEDURE DROP_ROLE(
    P_ROLENAME IN VARCHAR2
)
AUTHID CURRENT_USER 
AS
BEGIN
    EXECUTE IMMEDIATE ('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
    EXECUTE IMMEDIATE ('DROP ROLE ' || P_ROLENAME);
END;
/
-- THUC THI PROCEDURE CREATE_USER
BEGIN
    DROP_ROLE('QUANTRI_CSDL');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE HIEU CHINH ROLE
CREATE OR REPLACE PROCEDURE ALTER_ROLE(
    P_ROLENAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2
)
AUTHID CURRENT_USER 
AS
BEGIN
    EXECUTE IMMEDIATE ('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
    EXECUTE IMMEDIATE ('ALTER ROLE ' || P_ROLENAME ||' IDENTIFIED BY '||P_PASSWORD);
END;
/
-- THUC THI PROCEDURE ALTER_ROLE
BEGIN
    ALTER_ROLE('QUANTRI_CSDL','1');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- PHAN QUYEN CHO ROLE
CREATE OR REPLACE PROCEDURE GRANT_PRIVS_ROLE(
    P_ROLENAME IN VARCHAR2,
    P_PRIVSNAME IN VARCHAR2,
    P_OBJECTNAME IN VARCHAR2)
AUTHID CURRENT_USER
AS
BEGIN
    EXECUTE IMMEDIATE ('GRANT '||P_PRIVSNAME||' ON '||P_OBJECTNAME||' TO '||P_ROLENAME);
END;
/
-- THUC THI PROCEDURE GRANT_PRIVS_ROLE
BEGIN
    GRANT_PRIVS_ROLE('QUANTRI','EXECUTE','CREATE_USER');
END;
/
GRANT EXECUTE ON CREATE_ROLE TO QUANTRI_CSDL;
---------------------------------------------------------------------------------------------------------------------------
-- THU HOI QUYEN CUA ROLE
CREATE OR REPLACE PROCEDURE REVOKE_PRIVS_ROLE(
    P_ROLENAME IN VARCHAR2,
    P_PRIVSNAME IN VARCHAR2,
    P_OBJECTNAME IN VARCHAR2)
AUTHID CURRENT_USER
AS
BEGIN
    EXECUTE IMMEDIATE ('REVOKE '||P_PRIVSNAME||' ON '||P_OBJECTNAME||' FROM '||P_ROLENAME);
END;
/
-- THUC THI PROCEDURE GRANT_PRIVS_ROLE
BEGIN
    REVOKE_PRIVS_ROLE('QUANTRI_CSDL','SELECT','VIEW_USERS');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- PHAN QUYEN CHO USER
CREATE OR REPLACE PROCEDURE GRANT_PRIVS_USER(
    P_USERNAME IN VARCHAR2,
    P_PRIVSNAME IN VARCHAR2,
    P_OBJECTNAME IN VARCHAR2,
    GRANT_OPTION IN VARCHAR2)
AUTHID CURRENT_USER
AS
BEGIN
    IF(GRANT_OPTION = 'NO') THEN
        EXECUTE IMMEDIATE ('GRANT '||P_PRIVSNAME||' ON '||P_OBJECTNAME||' TO '||P_USERNAME);
    ELSIF(GRANT_OPTION = 'YES') THEN 
        EXECUTE IMMEDIATE ('GRANT '||P_PRIVSNAME||' ON '||P_OBJECTNAME||' TO '||P_USERNAME||' WITH GRANT OPTION ');
    ELSIF(P_OBJECTNAME = 'NONE') THEN
        EXECUTE IMMEDIATE ('GRANT '||P_PRIVSNAME||' TO '||P_USERNAME);
    END IF;
END;
/
-- THUC THI PROCEDURE GRANT_PRIVS_USER
BEGIN
    GRANT_PRIVS_USER('C##QUANTRI1','EXECUTE','ALTER_ROLE','YES');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- THU HOI QUYEN CUA USER
CREATE OR REPLACE PROCEDURE REVOKE_PRIVS_USER(
    P_USERNAME IN VARCHAR2,
    P_PRIVSNAME IN VARCHAR2,
    P_OBJECTNAME IN VARCHAR2)
AUTHID CURRENT_USER
AS
BEGIN
    EXECUTE IMMEDIATE ('REVOKE '||P_PRIVSNAME||' ON '||P_OBJECTNAME||' FROM '||P_USERNAME);
END;
/
-- THUC THI PROCEDURE REVOKE_PRIVS_USER
BEGIN
    REVOKE_PRIVS_USER('C##QUANTRI1','SELECT','VIEW_USERS');
END;
/
---------------------------------------------------------------------------------------------------------------------------
-- GAN ROLE CHO USER
CREATE OR REPLACE PROCEDURE GRANT_ROLE_TO_USER(
    P_ROLENAME IN VARCHAR2,
    P_USERNAME IN VARCHAR2)
AUTHID CURRENT_USER
AS
BEGIN
    EXECUTE IMMEDIATE ('GRANT '||P_ROLENAME||' TO '||P_USERNAME);
END;
/
-- THUC THI PROCEDURE GRANT_ROLE_TO_USER
BEGIN
    GRANT_ROLE_TO_USER('QUANTRI_CSDL','C##QUANTRI1');
END;
/
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT DROP USER TO C##QUANTRI1 WITH ADMIN OPTION;
REVOKE EXECUTE ON CREATE_USER FROM C##QUANTRI1;
GRANT EXECUTE ON CREATE_USER TO C##QUANTRI;

GRANT CREATE SESSION TO C##QUANTRI1;
GRANT ALL PRIVILEGES TO C##QUANTRI1;
