-- Connect with SYS AS SYSDBA account
ALTER SESSION SET CURRENT_SCHEMA = QL_TRUONGHOC_X;

SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security';
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS';
---> BAT OLS NEU CHUA BAT/ CHUA DANG KY THI DANG KY OLS VA BAT OLS
BEGIN
    LBACSYS.CONFIGURE_OLS;
    -- Các câu l?nh PL/SQL khác ? ?ây n?u c?n
END;

EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; -- This procedure enables it
---> KHOI DONG LAI
SHUTDOWN IMMEDIATE;
STARTUP;
---> KIEM TRA PDB CO CHUA (VI KO THE TAO OLS TREN CDB)
select * from v$services;
---> UNLOCK LBACSYS (OLS ADMIN)
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
SELECT * FROM DBA_PDBS WHERE pdb_name = 'XEPDB1';
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CONTAINER_NAME FROM DUAL;
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA FROM DUAL;

---> NEU CO ROI THI MO PDB
ALTER PLUGGABLE DATABASE XEPDB1 OPEN READ WRITE;
---> CHUYEN QUA PDB
ALTER SESSION SET CONTAINER= XEPDB1;
SHOW CON_NAME;
--DROP USER ADMIN_OLS CASCADE;
CREATE USER ADMIN_OLS IDENTIFIED BY 123 CONTAINER = CURRENT;

GRANT CONNECT,RESOURCE TO ADMIN_OLS; --CAP QUYEN CONNECT VA RESOURCE
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS; --CAP QUOTA CHO ADMIN_OLS
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS; --CAP QUYEN DOC DICTIONARY

---> CAP QUYEN EXECUTE CHO ADMIN_OLS
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION;
---> ADD ADMIN_OLS VÀO LBAC_DBA
GRANT LBAC_DBA TO ADMIN_OLS;
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS;
