-- init programm
alter session set "_ORACLE_SCRIPT"=true;

-- Xoá các user ?ã t?o tr??c ?ó 
DECLARE
    CURSOR CUR_USR IS ( 
        SELECT USERNAME FROM dba_users
        WHERE username like 'X_NS%' or username like 'X_SV%'
    );
BEGIN
    FOR USR IN CUR_USR LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.USERNAME || ' CASCADE';
    END LOOP;
END;
/
-- Xoá các role ?ã t?o tr??c ?ó 
DECLARE
    CURSOR CUR_RL IS ( 
        SELECT ROLE FROM dba_roles
        WHERE ROLE like 'RL_TRUONGHOC_%' 
    );
BEGIN
    FOR RL IN CUR_RL LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || RL.ROLE;
    END LOOP;
END;
/

-- T?o các role c? b?n 
CREATE ROLE RL_TRUONGHOC_NHANVIENCOBAN;
CREATE ROLE RL_TRUONGHOC_GIANGVIEN;
CREATE ROLE RL_TRUONGHOC_GIAOVU;
CREATE ROLE RL_TRUONGHOC_TRUONGDONVI;
CREATE ROLE RL_TRUONGHOC_TRUONGKHOA;
CREATE ROLE RL_TRUONGHOC_SINHVIEN;

-- T?o user cho Sinh Viên
CREATE OR REPLACE TRIGGER QL_TRUONGHOC_X.TR_CREATE_USER_FOR_STUDENT
AFTER INSERT ON QL_TRUONGHOC_X.SINHVIEN
FOR EACH ROW
DECLARE 
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_username VARCHAR2(50);
BEGIN
    -- Thêm ng??i dùng m?i vào h? th?ng
    v_username := 'X_' || :new.MASV;
    EXECUTE IMMEDIATE 'CREATE USER ' || v_username || ' IDENTIFIED BY 123';
    COMMIT;  
END;
/

CREATE OR REPLACE TRIGGER QL_TRUONGHOC_X.TR_CREATE_USER_FOR_EMPLOYEE
AFTER INSERT ON QL_TRUONGHOC_X.NHANSU
FOR EACH ROW
DECLARE 
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_username VARCHAR2(50);
BEGIN
    -- Thêm ng??i dùng m?i vào h? th?ng
    v_username := 'X_' || :new.MANV;
    EXECUTE IMMEDIATE 'CREATE USER ' || v_username || ' IDENTIFIED BY 123';
    COMMIT;  
END;
/

CREATE OR REPLACE TRIGGER QL_TRUONGHOC_X.TR_UPDATE_SOTINCHITICHLUY
AFTER INSERT ON QL_TRUONGHOC_X.DANGKY
FOR EACH ROW
DECLARE 
    PRAGMA AUTONOMOUS_TRANSACTION;
    sotc number(3,0);
BEGIN
    -- C?p nh?t thu?c tính SOTINCHITICHUY trong b?ng SINHVIEN
    SELECT SOTC INTO sotc
        FROM QL_TRUONGHOC_X.HOCPHAN hp 
        WHERE hp.MAHP = :new.MAHP and ROWNUM <= 1;
        
    UPDATE QL_TRUONGHOC_X.SINHVIEN sv
    SET sv.SOTCTL = sv.SOTCTL + sotc,
        sv.DTBTL = (sv.DTBTL * sv.SOTCTL + :new.DIEMTK * sotc) / ( sv.DTBTL * sv.SOTCTL +  sotc )
    WHERE sv.MASV = :new.MASV;
    COMMIT;  
END;
/

CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.USP_ASSIGN_ROLES(
    ROLE_NAME VARCHAR2, USERNAME VARCHAR2, TABLE_NAME VARCHAR2 ,ROLE_COLUMN VARCHAR2, ROLE_ID VARCHAR2
) 
AUTHID CURRENT_USER 
AS 
    CUR SYS_REFCURSOR;  -- Bi?n con tr?
    USERS VARCHAR2(7);  -- USERS
BEGIN
    OPEN CUR FOR 'SELECT ' || USERNAME || ' FROM ' || 'QL_TRUONGHOC_X.' || TABLE_NAME
        || ' WHERE ' || ROLE_COLUMN || ' = ''' || ROLE_ID || ''' AND ''X_'' || '
        || USERNAME || ' IN (SELECT USERNAME FROM ALL_USERS)';
    LOOP
        FETCH CUR INTO USERS;
        EXIT WHEN CUR%NOTFOUND;
        EXECUTE IMMEDIATE 'GRANT RL_TRUONGHOC_' || ROLE_NAME || ' TO X_' || USERS;
    END LOOP;
    CLOSE CUR;
END;

-- select * from dba_roles where role like 'RL_TRUONGHOC_%';
-- SELECT * FROM DBA_ROLE_PRIVS where GRANTED_ROLE like 'RL_TRUONGHOC_%';
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('NHANVIENCOBAN', 'MANV', 'NHANSU', 'VAITRO', 'Nhan vien co ban');

-- EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('NHANVIENCOBAN', 'MANV', 'NHANSU', 'VAITRO', 'Giang vien');
EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('GIANGVIEN', 'MANV', 'NHANSU', 'VAITRO', 'Giang vien');

EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('TRUONGKHOA', 'MANV', 'NHANSU', 'VAITRO', 'Truong khoa');
-- EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('NHANVIENCOBAN', 'MANV', 'NHANSU', 'VAITRO', 'Truong khoa');

EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('TRUONGDONVI', 'MANV', 'NHANSU', 'VAITRO', 'Truong don vi');
-- EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('NHANVIENCOBAN', 'MANV', 'NHANSU', 'VAITRO', 'Truong don vi');

EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('GIAOVU', 'MANV', 'NHANSU', 'VAITRO', 'Giao vu');
-- EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES('NHANVIENCOBAN', 'MANV', 'NHANSU', 'VAITRO', 'Giao vu');

CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.USP_ASSIGN_ROLES_NO_CONDITION(
    ROLE_NAME VARCHAR2, USERNAME VARCHAR2, TABLE_NAME VARCHAR2 
) 
AUTHID CURRENT_USER 
AS 
    CUR SYS_REFCURSOR;  -- Bi?n con tr?
    USERS VARCHAR2(10);  -- USERS
BEGIN
    OPEN CUR FOR 'SELECT ' || USERNAME || ' FROM ' || 'QL_TRUONGHOC_X.' || TABLE_NAME
        || ' WHERE ''X_'' || ' || USERNAME || ' IN (SELECT USERNAME FROM ALL_USERS)';
    LOOP
        FETCH CUR INTO USERS;
        EXIT WHEN CUR%NOTFOUND;
        EXECUTE IMMEDIATE 'GRANT RL_TRUONGHOC_' || ROLE_NAME || ' TO X_' || USERS;
    END LOOP;
    CLOSE CUR;
END;

EXEC QL_TRUONGHOC_X.USP_ASSIGN_ROLES_NO_CONDITION('SINHVIEN', 'MASV', 'SINHVIEN');
-- SELECT count(*) FROM DBA_ROLE_PRIVS where GRANTED_ROLE like 'RL_TRUONGHOC_SINHVIEN';

