--Nguoi dung co vai tro Truong khoa co quyen han
--1. Nhu mot nguoi dung co vai tro Giang vien
GRANT RL_TRUONGHOC_GIANGVIEN TO RL_TRUONGHOC_TRUONGKHOA;

--2. Them, xoa, cap nhat du lieu tren quan he 

--THEM DU LIEU
CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.TRUONGKHOA_INSERT_PHANCONG
(
    p_MAGV PHANCONG.MAGV%TYPE,
    p_MAHP PHANCONG.MAHP%TYPE,
    p_HK PHANCONG.HK%TYPE,
    p_NAM PHANCONG.NAM%TYPE,
    p_MACT PHANCONG.MACT%TYPE
)
AS
    V_CURRENT_USER VARCHAR2(10);
    V_MANV VARCHAR2(12);
    l_count NUMBER;
BEGIN
    V_CURRENT_USER := SYS_CONTEXT('USERENV', 'SESSION_USER');
    SELECT MANV INTO V_MANV FROM QL_TRUONGHOC_X.NHANSU WHERE 'X_' || MANV = V_CURRENT_USER;
    
    IF V_MANV IS NOT NULL THEN
        SELECT COUNT(*)
        INTO l_count
        FROM HOCPHAN HP JOIN DONVI DV ON HP.MADV = DV.MADV
        WHERE HP.MAHP = p_MAHP AND DV.TENDV = N'Van phong khoa';

        IF l_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Ma hoc phan khong thuoc van phong khoa');
        ELSE
            INSERT INTO PHANCONG(MAGV, MAHP, HK, NAM, MACT)
            VALUES (p_MAGV, p_MAHP, p_HK, p_NAM, p_MACT);
            COMMIT;
        END IF;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
/

--XOA DU LIEU
CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.TRUONGKHOA_DELETE_PHANCONG
(
    p_MAHP PHANCONG.MAHP%TYPE
)
AS
    V_CURRENT_USER varchar2(10);
    V_MANV varchar2(12);
    l_count NUMBER;
BEGIN
    V_CURRENT_USER := SYS_CONTEXT('USERENV', 'SESSION_USER');
    SELECT MANV INTO V_MANV FROM QL_TRUONGHOC_X.NHANSU WHERE 'X_' || MANV = V_CURRENT_USER;
    IF V_MANV IS NOT NULL THEN
        SELECT COUNT(*)
        INTO l_count
        FROM PHANCONG PC
        JOIN HOCPHAN HP ON PC.MAHP = HP.MAHP
        JOIN DONVI DV ON HP.MADV = DV.MADV
        WHERE PC.MAHP = p_MAHP AND DV.TENDV = 'Van phong khoa';
        
        IF l_count = 0 THEN
            RAISE_APPLICATION_ERROR (-20002, 'Du lieu can xoa khong ton tai trong he thong.');
        END IF;
        DELETE FROM PHANCONG
        WHERE MAHP = p_MAHP;
        
        COMMIT;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

--CAP NHAT DU LIEU
CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.TRUONGKHOA_UPDATE_PHANCONG(
    p_MAHP PHANCONG.MAHP%TYPE,
    p_NEW_MAGV PHANCONG.MAGV%TYPE,
    p_NEW_HK PHANCONG.HK%TYPE,
    p_NEW_NAM PHANCONG.NAM%TYPE,
    p_NEW_MACT PHANCONG.MACT%TYPE
)
AS
    V_CURRENT_USER varchar2(10);
    V_MANV varchar2(12);
    l_count number;
BEGIN
    V_CURRENT_USER := SYS_CONTEXT('USERENV', 'SESSION_USER');
    SELECT MANV INTO V_MANV FROM QL_TRUONGHOC_X.NHANSU WHERE 'X_' || MANV = V_CURRENT_USER;
    IF V_MANV IS NOT NULL THEN
        SELECT COUNT(*)
        INTO l_count
        FROM PHANCONG PC
        JOIN HOCPHAN HP ON PC.MAHP = HP.MAHP
        JOIN DONVI DV ON HP.MADV = DV.MADV
        WHERE PC.MAHP = p_MAHP AND DV.TENDV = 'Van phong khoa';
        
        IF l_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20004, 'Khong tim thay du lieu can cap nhat.');
        END IF;
        
        UPDATE PHANCONG
        SET MAGV = p_NEW_MAGV, HK = p_NEW_HK, NAM = p_NEW_NAM, MACT = p_NEW_MACT
        WHERE MAHP = p_MAHP;
        COMMIT;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE VIEW QL_TRUONGHOC_X.PHANCONG_CHITIET AS
    SELECT ns.manv, hp.mahp, ns.hoten, hp.tenhp, pc.hk, pc.nam, pc.mact  FROM QL_TRUONGHOC_X.PHANCONG pc
    JOIN QL_TRUONGHOC_X.NHANSU ns  ON pc.MAGV = ns.MANV
    JOIN QL_TRUONGHOC_X.HOCPHAN hp ON pc.MAHP = hp.MAHP;
    
CREATE OR REPLACE VIEW QL_TRUONGHOC_X.PHANCONG_CHITIET_VPK AS
    SELECT ns.manv, hp.mahp, ns.hoten, hp.tenhp, pc.hk, pc.nam, pc.mact  FROM QL_TRUONGHOC_X.PHANCONG pc
    JOIN QL_TRUONGHOC_X.NHANSU ns  ON pc.MAGV = ns.MANV
    JOIN QL_TRUONGHOC_X.HOCPHAN hp ON pc.MAHP = hp.MAHP
    WHERE hp.madv = 'VPK01';
    
CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.TRUONGKHOA_INSERT_NHANSU(
    MANV char,
    HOTEN varchar2,
    PHAI char, 
    NGAYSINH varchar2,
    PHUCAP number,
    DT char,
    VAITRO varchar2, 
    MADV char
)
AS
BEGIN
    insert into QL_TRUONGHOC_X.NHANSU
    select MANV, HOTEN, PHAI, TO_DATE(NGAYSINH,'DD/MM/YY'), PHUCAP, DT, VAITRO, MADV from dual;
    commit;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.TRUONGKHOA_DELETE_NHANSU(
    MANV char
)
AS
BEGIN
    delete from QL_TRUONGHOC_X.NHANSU
    where MANV = MANV;
    commit;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
    
CREATE OR REPLACE PROCEDURE QL_TRUONGHOC_X.TRUONGKHOA_UPDATE_NHANSU(
    MANV char,
    HOTEN varchar2,
    PHAI char, 
    NGAYSINH varchar2,
    PHUCAP number,
    DT char,
    VAITRO varchar2, 
    MADV char
)
AS
BEGIN
    update QL_TRUONGHOC_X.NHANSU
    set 
        HOTEN = HOTEN,
        PHAI = PHAI, 
        NGAYSINH = NGAYSINH,
        PHUCAP = PHUCAP,
        DT = DT,
        VAITRO = VAITRO, 
        MADV = MADV
    where MANV = MANV;
    commit;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


GRANT EXECUTE ON QL_TRUONGHOC_X.TRUONGKHOA_UPDATE_NHANSU TO RL_TRUONGHOC_TRUONGKHOA;
GRANT EXECUTE ON QL_TRUONGHOC_X.TRUONGKHOA_DELETE_NHANSU TO RL_TRUONGHOC_TRUONGKHOA;
GRANT EXECUTE ON QL_TRUONGHOC_X.TRUONGKHOA_INSERT_NHANSU TO RL_TRUONGHOC_TRUONGKHOA;

GRANT EXECUTE ON QL_TRUONGHOC_X.TRUONGKHOA_INSERT_PHANCONG TO RL_TRUONGHOC_TRUONGKHOA;
GRANT EXECUTE ON QL_TRUONGHOC_X.TRUONGKHOA_DELETE_PHANCONG TO RL_TRUONGHOC_TRUONGKHOA;
GRANT EXECUTE ON QL_TRUONGHOC_X.TRUONGKHOA_UPDATE_PHANCONG TO RL_TRUONGHOC_TRUONGKHOA;


--Duoc quyen Xem, them , xoa, cap nhat tren quan he NHANSU
GRANT SELECT, INSERT, DELETE, UPDATE ON NHANSU TO RL_TRUONGHOC_TRUONGKHOA;

--Duoc quyen xem (khong gioi han) du lieu tren toan bo luoc do CDSL
GRANT SELECT ANY TABLE TO RL_TRUONGHOC_TRUONGKHOA;


GRANT SELECT ON QL_TRUONGHOC_X.DONVI_CHITIET TO RL_TRUONGHOC_TRUONGKHOA;
GRANT SELECT ON QL_TRUONGHOC_X.KHMO_CHITIET TO RL_TRUONGHOC_TRUONGKHOA;
GRANT SELECT ON QL_TRUONGHOC_X.PHANCONG_CHITIET TO RL_TRUONGHOC_TRUONGKHOA;




hello  g???